### PR TITLE
Update frontend

### PR DESCRIPTION
**Pull request by KennethAshley**
Hey! I updated the Frontend. I hope you don't mind some of the liberties I took. i.e. folder structure, styling, etc. I just updated the initial connection components.

I left this PR as a draft PR because it's not ready to be merged in yet. Just wanted to get everyone's opinion.

@alexroan @jacob-eliosoff

### CODE REVIEW

**Comment by albertocuestacanada** [comment]
Hey @KennethAshley, thanks for doing this! It's there any way for me and Jacob to see the frontend without running the code? Something like a video or a website?

**Comment by KennethAshley** [comment]
@albertocuestacanada hmmm I can try to add it to netlify. In the meantime here are a few screenshots

image

**Button Hover**
image

**Comment by alexroan** [comment]
Nice work. I like the style! Looking forward to seeing it when the rest is done.

Are you planning on working on the web3 interactions on this PR also?

**Comment by KennethAshley** [comment]
@alexroan yea I can do that as well. I just didn't want to head in a direction that yall didn't like. I kept it really really minimal.

**Comment by alexroan** [comment]
Hey Kenneth, are you still working on this?

**Comment by KennethAshley** [comment]
@alexroan Yes, I am. I went on vacation but I'm back now.

**Pull request closed without merging**
